using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]

public class TestGameData
{
    public int score = 0;

    public int AddScore(int points)
    {
        return(score += points);
    }

    public void ResetData()
    {
        score = 0;
    }

    // Only basic datatypes can be saved into serializable forms
    // Arrays are allowed, for multidimensional arrays (ones that look like [,] or [,,,]), instead 'stagger' them: https://forum.unity.com/threads/how-i-serialize-multidimensional-arrays.988704/
    // Unity based datatypes, ie. GameObject, Vector3, Color, etc. cannot be serialized. These should be generated by a script using stored serialized data, ie. Vector3 jeffvec = new Vector3(storedIntA, storedIntB, storedIntC);
}